apiVersion: batch/v1
kind: Job
metadata:
  name: gang
spec:
  completions: 7
  parallelism: 7
  template:
    spec:
      containers:
      - name: gang
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: cmName
          value: "{{ .Values.gang.configName }}"
        - name: cmNamespace
          value: "{{ .Values.gang.configNamespace }}"
        - name: dataName
          value: "{{ .Values.gang.dataName }}"
        command: ["go"]
        args: ["mod", "download"]
        command: ["go"]
        args: ["run", "main.go"]
      restartPolicy: Never